//////////////////////////////////
// Class enums

import { CategoryObject } from "./Objects/CategoryObject";
import { TypeObject } from "./Objects/TypeObject";

export type CategoryClass =
  | "buildingCategory"
  | "equipmentCategory"
  | "goalCategory"
  | "godCategory"
  | "heritageCategory"
  | "improvementCategory"
  | "majorCultureCategory"
  | "majorLeaderCategory"
  | "minorCultureCategory"
  | "minorLeaderCategory"
  | "mythCategory"
  | "nationalWonderCategory"
  | "naturalWonderCategory"
  | "platformCategory"
  | "policyCategory"
  | "regionCategory"
  | "resourceCategory"
  | "stockpileCategory"
  | "technologyCategory"
  | "traitCategory"
  | "worldWonderCategory";

export type TypeClass =
  | "actionType"
  | "buildingType"
  | "climateType"
  | "conceptType"
  | "continentType"
  | "dogmaType"
  | "domainType"
  | "elevationType"
  | "equipmentType"
  | "eraType"
  | "eventType"
  | "featureType"
  | "goalType"
  | "godType"
  | "heritageType"
  | "improvementType"
  | "majorCultureType"
  | "majorLeaderType"
  | "minorCultureType"
  | "minorLeaderType"
  | "mythType"
  | "nationalWonderType"
  | "naturalWonderType"
  | "oceanType"
  | "platformType"
  | "policyType"
  | "regionType"
  | "resourceType"
  | "routeType"
  | "specialType"
  | "stockpileType"
  | "technologyType"
  | "terrainType"
  | "traitType"
  | "worldWonderType"
  | "yieldType";

//////////////////////////////////
// Key enums

export type CatKey = `${CategoryClass}:${string}`;
export type TypeKey = `${TypeClass}:${string}`;
export type StaticKey = CatKey | TypeKey;

export type ActionTypeKey =
  | "actionType:move"
  | "actionType:explore"
  | "actionType:skipTurn"
  | "actionType:fortify"
  | "actionType:heal"
  | "actionType:build"
  | "actionType:repair"
  | "actionType:settle"
  | "actionType:trade"
  | "actionType:initiateAction"
  | "actionType:attack"
  | "actionType:pillage"
  | "actionType:bombard"
  | "actionType:togglePiracy"
  | "actionType:recon"
  | "actionType:patrol"
  | "actionType:paradrop"
  | "actionType:delete";

export type ConceptTypeKey =
  | "conceptType:action"
  | "conceptType:agenda"
  | "conceptType:building"
  | "conceptType:construction"
  | "conceptType:citizen"
  | "conceptType:city"
  | "conceptType:climate"
  | "conceptType:concept"
  | "conceptType:continent"
  | "conceptType:culture"
  | "conceptType:deal"
  | "conceptType:dogma"
  | "conceptType:domain"
  | "conceptType:elevation"
  | "conceptType:equipment"
  | "conceptType:era"
  | "conceptType:event"
  | "conceptType:feature"
  | "conceptType:flatLand"
  | "conceptType:freshWater"
  | "conceptType:goal"
  | "conceptType:god"
  | "conceptType:government"
  | "conceptType:heritage"
  | "conceptType:improvement"
  | "conceptType:interaction"
  | "conceptType:majorCulture"
  | "conceptType:majorLeader"
  | "conceptType:minorCulture"
  | "conceptType:minorLeader"
  | "conceptType:mountains"
  | "conceptType:myth"
  | "conceptType:nationalWonder"
  | "conceptType:naturalWonder"
  | "conceptType:navigableRiver"
  | "conceptType:ocean"
  | "conceptType:platform"
  | "conceptType:player"
  | "conceptType:policy"
  | "conceptType:region"
  | "conceptType:religion"
  | "conceptType:research"
  | "conceptType:resource"
  | "conceptType:revolution"
  | "conceptType:river"
  | "conceptType:route"
  | "conceptType:special"
  | "conceptType:stockpile"
  | "conceptType:technology"
  | "conceptType:terrain"
  | "conceptType:tile"
  | "conceptType:tradeRoute"
  | "conceptType:trait"
  | "conceptType:turn"
  | "conceptType:turnStart"
  | "conceptType:unit"
  | "conceptType:unitDesign"
  | "conceptType:urban"
  | "conceptType:world"
  | "conceptType:worldWonder"
  | "conceptType:yield";

export type SpecialTypeKey =
  | "specialType:againstYourIncident"
  | "specialType:allCities"
  | "specialType:allCitiesWithRailroad"
  | "specialType:allCitiesWithRiver"
  | "specialType:allInTile"
  | "specialType:canBuildSatellites"
  | "specialType:canCarryStockpile"
  | "specialType:canEnterIce"
  | "specialType:canEnterMountains"
  | "specialType:canEnterOcean"
  | "specialType:canEnterSea"
  | "specialType:canHoldTournaments"
  | "specialType:canLandOnCarrier"
  | "specialType:canLevy"
  | "specialType:canMobilize"
  | "specialType:canMoveAfterAttack"
  | "specialType:canSelectTarget"
  | "specialType:cannotAttackWater"
  | "specialType:cannotBeAttacked"
  | "specialType:cannotBuildUnits"
  | "specialType:cannotBuyBuildings"
  | "specialType:cannotDeclineTrade"
  | "specialType:cannotEnter"
  | "specialType:cannotKillLandUnits"
  | "specialType:cannotTradeNonAllies"
  | "specialType:chooseFreeTechnology"
  | "specialType:damagesAllUnitsInTile"
  | "specialType:damagesBuildings"
  | "specialType:damagesImprovements"
  | "specialType:distanceFromCapital"
  | "specialType:elections"
  | "specialType:forceAutomaticBuildQueue"
  | "specialType:forcedStateReligion"
  | "specialType:ignoreMoveCost"
  | "specialType:invisibleBeforeMove"
  | "specialType:landUnitsCanEnter"
  | "specialType:maxPerCity"
  | "specialType:mustBeInAirbase"
  | "specialType:nextToCoast"
  | "specialType:nextToNavigableRiver"
  | "specialType:noDefenseBonuses"
  | "specialType:noDesertDamage"
  | "specialType:noJungleDamage"
  | "specialType:noSnowDamage"
  | "specialType:noStateReligion"
  | "specialType:onlyOnResource"
  | "specialType:pillageRange"
  | "specialType:shipsCanEnter"
  | "specialType:singleUse"
  | "specialType:startSize"
  | "specialType:stockpiled";

export type CatData = {
  category: CategoryObject;
  types: Set<TypeObject>;
};
